# Generated by Django 3.2.8 on 2021-10-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
